/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of FTDId2xx.xs. Do not edit this file, edit FTDId2xx.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "FTDId2xx.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

// project includes
#include <ftd2xx.h>
 // #include "p5ftd2xx.h"

// system includes
#include "WinTypes.h"
#include <stdlib.h>
#include <strings.h>

// #define DEBUG 1

// written on linux (debian) for ftdi d2xx version 0.4.16
//


#line 32 "FTDId2xx.c"
XS(XS_FTDId2xx_FT_Open); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_Open)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_Open(deviceNumber, pHandle)");
    {
	int	deviceNumber = (int)SvIV(ST(0));
	FT_HANDLE *	pHandle;
	FT_STATUS	RETVAL;
	dXSTARG;
#line 31 "FTDId2xx.xs"
		pHandle = malloc(sizeof(FT_HANDLE));
		RETVAL = FT_Open( deviceNumber, pHandle);

#line 48 "FTDId2xx.c"
	sv_setref_pv(ST(1), Nullch, (void*)pHandle);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_OpenEx); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_OpenEx)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_OpenEx(Arg1, Flags, pHandle)");
    {
	SV *	Arg1 = ST(0);
	DWORD	Flags = (DWORD)SvUV(ST(1));
	FT_HANDLE *	pHandle;
	FT_STATUS	RETVAL;
	dXSTARG;
#line 44 "FTDId2xx.xs"
		DWORD pArg1D;
		PVOID pArg1P;
#line 71 "FTDId2xx.c"
#line 47 "FTDId2xx.xs"
		pHandle = malloc(sizeof(FT_HANDLE));
		if((Flags != FT_OPEN_BY_SERIAL_NUMBER) 
			&& (Flags != FT_OPEN_BY_DESCRIPTION )) {
			// pArg1 equals ID number
			pArg1D = (DWORD)SvUV(Arg1);
			RETVAL = FT_OpenEx( &pArg1D, Flags, pHandle );
		} else {
			// pArg1 equals pointer to string
			pArg1P = SvPV_nolen(Arg1); // Convert to string
			RETVAL = FT_OpenEx( pArg1P, Flags, pHandle );

		}
#line 85 "FTDId2xx.c"
	sv_setref_pv(ST(2), Nullch, (void*)pHandle);
	SvSETMAGIC(ST(2));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_Close); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_Close)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_Close(ftHandle)");
    {
	FT_HANDLE *	ftHandle;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    ftHandle = INT2PTR(FT_HANDLE *,tmp);
	}
	else
	    Perl_croak(aTHX_ "ftHandle is not a reference");
#line 67 "FTDId2xx.xs"
		RETVAL=FT_Close( *ftHandle );
		free(ftHandle);
#line 113 "FTDId2xx.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_CreateDeviceInfoList); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_CreateDeviceInfoList)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_CreateDeviceInfoList(NumDevs)");
    {
	DWORD	NumDevs;
	FT_STATUS	RETVAL;
	dXSTARG;
#line 80 "FTDId2xx.xs"
		RETVAL = FT_CreateDeviceInfoList( &NumDevs );
#line 131 "FTDId2xx.c"
	sv_setuv(ST(0), (UV)NumDevs);
	SvSETMAGIC(ST(0));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetDeviceInfoDetail); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetDeviceInfoDetail)
{
    dXSARGS;
    if (items != 8)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetDeviceInfoDetail(dwIndex, dwFlags, dwType, dwID, dwLocId, SerialNumber, Description, pftHandle)");
    {
	DWORD	dwIndex = (DWORD)SvUV(ST(0));
	DWORD	dwFlags;
	DWORD	dwType;
	DWORD	dwID;
	DWORD	dwLocId;
	SV *	SerialNumber;
	SV *	Description;
	FT_HANDLE *	pftHandle;
	FT_STATUS	RETVAL;
	dXSTARG;
#line 98 "FTDId2xx.xs"
		char * lpSerialNumber;
		char * lpDescription;
#line 159 "FTDId2xx.c"
#line 101 "FTDId2xx.xs"
		pftHandle = malloc(sizeof(FT_HANDLE));
		lpSerialNumber = malloc(16);
		lpDescription = malloc(64);
		RETVAL = FT_GetDeviceInfoDetail( dwIndex, &dwFlags, &dwType, &dwID, &dwLocId, lpSerialNumber, lpDescription, pftHandle);
		SerialNumber = sv_2mortal(newSVpv(lpSerialNumber,16));
		free(lpSerialNumber);
		Description = sv_2mortal(newSVpv(lpDescription,64));
		free(lpDescription);
#line 169 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)dwFlags);
	SvSETMAGIC(ST(1));
	sv_setuv(ST(2), (UV)dwType);
	SvSETMAGIC(ST(2));
	sv_setuv(ST(3), (UV)dwID);
	SvSETMAGIC(ST(3));
	sv_setuv(ST(4), (UV)dwLocId);
	SvSETMAGIC(ST(4));
	ST(5) = SerialNumber;
	SvSETMAGIC(ST(5));
	ST(6) = Description;
	SvSETMAGIC(ST(6));
	sv_setref_pv(ST(7), Nullch, (void*)pftHandle);
	SvSETMAGIC(ST(7));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetDriverVersion); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetDriverVersion)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetDriverVersion(ftHandle, dwVersion)");
    {
	FT_HANDLE	ftHandle;
	DWORD	dwVersion;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 123 "FTDId2xx.xs"
		RETVAL = FT_GetDriverVersion( ftHandle, &dwVersion);
#line 209 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)dwVersion);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetLibraryVersion); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetLibraryVersion)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetLibraryVersion(dwVersion)");
    {
	DWORD	dwVersion;
	FT_STATUS	RETVAL;
	dXSTARG;
#line 132 "FTDId2xx.xs"
		RETVAL = FT_GetLibraryVersion( &dwVersion );
#line 229 "FTDId2xx.c"
	sv_setuv(ST(0), (UV)dwVersion);
	SvSETMAGIC(ST(0));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetVIDPID); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetVIDPID)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetVIDPID(dwVID, dwPID)");
    {
	DWORD	dwVID = (DWORD)SvUV(ST(0));
	DWORD	dwPID = (DWORD)SvUV(ST(1));
	FT_STATUS	RETVAL;
	dXSTARG;

	RETVAL = FT_SetVIDPID(dwVID, dwPID);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetVIDPID); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetVIDPID)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetVIDPID(dwVID, dwPID)");
    {
	DWORD	dwVID;
	DWORD	dwPID;
	FT_STATUS	RETVAL;
	dXSTARG;
#line 150 "FTDId2xx.xs"
		RETVAL = FT_GetVIDPID(&dwVID, &dwPID);
#line 268 "FTDId2xx.c"
	sv_setuv(ST(0), (UV)dwVID);
	SvSETMAGIC(ST(0));
	sv_setuv(ST(1), (UV)dwPID);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_Read); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_Read)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_Read(pHandle, Buffer, nBufferSize, lpBytesReturned)");
    {
	FT_HANDLE *	pHandle;
	SV *	Buffer;
	DWORD	nBufferSize = (DWORD)SvUV(ST(2));
	DWORD	lpBytesReturned;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
	    IV tmp = SvIV((SV*)SvRV(ST(0)));
	    pHandle = INT2PTR(FT_HANDLE *,tmp);
	}
	else
	    Perl_croak(aTHX_ "pHandle is not a reference");
#line 163 "FTDId2xx.xs"
		char *lpBuffer;
		AV * array;
		DWORD i;
#line 302 "FTDId2xx.c"
#line 167 "FTDId2xx.xs"
		// get mem
		lpBuffer = malloc(nBufferSize);
		RETVAL = FT_Read(*pHandle, lpBuffer, nBufferSize, &lpBytesReturned);

		// convert output to array
		// new array
		array = (AV *)sv_2mortal((SV *)newAV());
		// extend it ( not required but faster) 
		av_extend(array,lpBytesReturned);
		// copy to array
		for( i = 0; i< lpBytesReturned; i++) {
			av_push(array,newSVuv(lpBuffer[i]));
		}
		// give back mem
		free(lpBuffer);
		// return reference of the array
		Buffer = newRV((SV *) array);
#line 321 "FTDId2xx.c"
	ST(1) = Buffer;
	SvSETMAGIC(ST(1));
	sv_setuv(ST(3), (UV)lpBytesReturned);
	SvSETMAGIC(ST(3));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_Write); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_Write)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_Write(ftHandle, Buffer, nBufferSize, BytesWritten)");
    {
	FT_HANDLE	ftHandle;
	SV *	Buffer = ST(1);
	DWORD	nBufferSize = (DWORD)SvUV(ST(2));
	DWORD	BytesWritten;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 196 "FTDId2xx.xs"
		AV * arrayBuffer;
		char * lpBuffer;
		DWORD i;

		if( (!SvROK(Buffer)) 
			|| (SvTYPE(SvRV(Buffer)) != SVt_PVAV) 
			|| !(av_len((AV *)SvRV(Buffer)) < nBufferSize)) 
		{
			printf("Data type error\n");
			printf("!SvROK(Buffer): %d\n",!SvROK(Buffer));
			printf("(SvTYPE(SvRV(Buffer)) != SVt_PVAV) %di\n", (SvTYPE(SvRV(Buffer)) != SVt_PVAV));
			printf("av_len((AV *)SvRV(Buffer)): %d\n", av_len((AV *)SvRV(Buffer)));

			XSRETURN_UNDEF;
		}
#line 367 "FTDId2xx.c"
#line 212 "FTDId2xx.xs"
		// copy from array (reference) to buffer
		lpBuffer = malloc(nBufferSize);
		arrayBuffer = (AV *)SvRV(Buffer);
		for(i=0; i<nBufferSize;i++) {
			lpBuffer[i] = (char)SvUV(*av_fetch(arrayBuffer,i,0));
			printf("FT_Write buffer [%i] = %X\n", i, lpBuffer[i]);
		}
		RETVAL = FT_Write( ftHandle, lpBuffer, nBufferSize, &BytesWritten);
		free(lpBuffer);
#line 378 "FTDId2xx.c"
	sv_setuv(ST(3), (UV)BytesWritten);
	SvSETMAGIC(ST(3));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetBaudRate); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetBaudRate)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetBaudRate(ftHandle, BaudRate)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	ULONG	BaudRate = (ULONG)SvUV(ST(1));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetBaudRate(ftHandle, BaudRate);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetDivisor); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetDivisor)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetDivisor(ftHandle, Divisor)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	USHORT	Divisor = (USHORT)SvUV(ST(1));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetDivisor(ftHandle, Divisor);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetDataCharacteristics); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetDataCharacteristics)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetDataCharacteristics(ftHandle, WordLength, StopBits, Parity)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	UCHAR	WordLength = (UCHAR)SvUV(ST(1));
	UCHAR	StopBits = (UCHAR)SvUV(ST(2));
	UCHAR	Parity = (UCHAR)SvUV(ST(3));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetDataCharacteristics(ftHandle, WordLength, StopBits, Parity);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetFlowControl); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetFlowControl)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetFlowControl(ftHandle, FlowControl, XonChar, XoffChar)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	USHORT	FlowControl = (USHORT)SvUV(ST(1));
	UCHAR	XonChar = (UCHAR)SvUV(ST(2));
	UCHAR	XoffChar = (UCHAR)SvUV(ST(3));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetFlowControl(ftHandle, FlowControl, XonChar, XoffChar);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_ResetDevice); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_ResetDevice)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_ResetDevice(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_ResetDevice(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetDtr); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetDtr)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetDtr(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetDtr(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_ClrDtr); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_ClrDtr)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_ClrDtr(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_ClrDtr(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetRts); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetRts)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetRts(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetRts(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_ClrRts); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_ClrRts)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_ClrRts(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_ClrRts(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetModemStatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetModemStatus)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetModemStatus(ftHandle, ModemStatus)");
    {
	FT_HANDLE	ftHandle;
	ULONG	ModemStatus;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 271 "FTDId2xx.xs"
		RETVAL = FT_GetModemStatus( ftHandle,&ModemStatus );
#line 630 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)ModemStatus);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetChars); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetChars)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetChars(ftHandle, EventChar, EventCharEnabled, ErrorChar, ErrorCharEnabled)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	UCHAR	EventChar = (UCHAR)SvUV(ST(1));
	UCHAR	EventCharEnabled = (UCHAR)SvUV(ST(2));
	UCHAR	ErrorChar = (UCHAR)SvUV(ST(3));
	UCHAR	ErrorCharEnabled = (UCHAR)SvUV(ST(4));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetChars(ftHandle, EventChar, EventCharEnabled, ErrorChar, ErrorCharEnabled);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_Purge); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_Purge)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_Purge(ftHandle, Mask)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	ULONG	Mask = (ULONG)SvUV(ST(1));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_Purge(ftHandle, Mask);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetTimeouts); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetTimeouts)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetTimeouts(ftHandle, ReadTimeout, WriteTimeout)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	ULONG	ReadTimeout = (ULONG)SvUV(ST(1));
	ULONG	WriteTimeout = (ULONG)SvUV(ST(2));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetTimeouts(ftHandle, ReadTimeout, WriteTimeout);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetQueueStatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetQueueStatus)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetQueueStatus(ftHandle, RxBytes)");
    {
	FT_HANDLE	ftHandle;
	DWORD	RxBytes;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 289 "FTDId2xx.xs"
		RETVAL = FT_GetQueueStatus( ftHandle, &RxBytes);
#line 737 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)RxBytes);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetStatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetStatus)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetStatus(ftHandle, RxBytes, TxBytes, EventDWord)");
    {
	FT_HANDLE	ftHandle;
	DWORD	RxBytes;
	DWORD	TxBytes;
	DWORD	EventDWord;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 304 "FTDId2xx.xs"
		RETVAL = FT_GetStatus(ftHandle, &RxBytes, &TxBytes, &EventDWord);
#line 767 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)RxBytes);
	SvSETMAGIC(ST(1));
	sv_setuv(ST(2), (UV)TxBytes);
	SvSETMAGIC(ST(2));
	sv_setuv(ST(3), (UV)EventDWord);
	SvSETMAGIC(ST(3));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetBreakOn); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetBreakOn)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetBreakOn(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetBreakOn(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetBreakOff); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetBreakOff)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetBreakOff(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetBreakOff(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetWaitMask); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetWaitMask)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetWaitMask(ftHandle, Mask)");
    {
	FT_HANDLE	ftHandle;
	DWORD	Mask = (DWORD)SvUV(ST(1));
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetWaitMask(ftHandle, Mask);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_WaitOnMask); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_WaitOnMask)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_WaitOnMask(ftHandle, Mask)");
    {
	FT_HANDLE	ftHandle;
	DWORD	Mask;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 325 "FTDId2xx.xs"
		RETVAL = FT_WaitOnMask(ftHandle, &Mask);
#line 872 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)Mask);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetEventStatus); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetEventStatus)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetEventStatus(ftHandle, EventDWord)");
    {
	FT_HANDLE	ftHandle;
	DWORD	EventDWord;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 334 "FTDId2xx.xs"
	RETVAL = FT_GetEventStatus( ftHandle, &EventDWord);
#line 900 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)EventDWord);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_ReadEE); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_ReadEE)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_ReadEE(ftHandle, dwWordOffset, Value)");
    {
	FT_HANDLE	ftHandle;
	DWORD	dwWordOffset = (DWORD)SvUV(ST(1));
	WORD	Value;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 345 "FTDId2xx.xs"
		RETVAL = FT_ReadEE( ftHandle, dwWordOffset, &Value);
#line 929 "FTDId2xx.c"
	sv_setuv(ST(2), (UV)Value);
	SvSETMAGIC(ST(2));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_WriteEE); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_WriteEE)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_WriteEE(ftHandle, dwWordOffset, wValue)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	DWORD	dwWordOffset = (DWORD)SvUV(ST(1));
	WORD	wValue = (WORD)SvUV(ST(2));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_WriteEE(ftHandle, dwWordOffset, wValue);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_EraseEE); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_EraseEE)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_EraseEE(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_EraseEE(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_EE_ProgramByArray); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_EE_ProgramByArray)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_EE_ProgramByArray(ftHandle, Data)");
    {
	FT_HANDLE	ftHandle;
	SV *	Data = ST(1);
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 363 "FTDId2xx.xs"
		// Data is a reference of a array
		AV * arrayBuffer;
		char * pData;
		DWORD i;

		if( (!SvROK(Data)) || 
			(SvTYPE(SvRV(Data)) != SVt_PVAV) || 
			(av_len((AV *)SvRV(Data)) < 0)) 
		{
			XSRETURN_UNDEF;
		}
#line 1017 "FTDId2xx.c"
#line 375 "FTDId2xx.xs"
		// copy from array (reference) to buffer
		pData = malloc(sizeof(FT_PROGRAM_DATA));
		arrayBuffer = (AV *)SvRV(Data);
		for(i=0; i<sizeof(FT_PROGRAM_DATA);i++) {
			pData[i] = (char)SvUV(*av_fetch(arrayBuffer,i,0));
		}
		RETVAL = FT_EE_Program(ftHandle, (PFT_PROGRAM_DATA)pData);
		free(pData);
#line 1027 "FTDId2xx.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_EE_ReadToArray); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_EE_ReadToArray)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_EE_ReadToArray(ftHandle, Data)");
    {
	FT_HANDLE	ftHandle;
	SV *	Data;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 396 "FTDId2xx.xs"
		char *lpBuffer;
		AV * array;
		DWORD i;
#line 1055 "FTDId2xx.c"
#line 400 "FTDId2xx.xs"
		// get mem
		lpBuffer = malloc(sizeof(FT_PROGRAM_DATA));
		RETVAL = FT_EE_Read(ftHandle, (PFT_PROGRAM_DATA)lpBuffer);

		// convert output to array
		// new array
		array = (AV *)sv_2mortal((SV *)newAV());
		// extend it ( not required but faster) 
		av_extend(array,sizeof(FT_PROGRAM_DATA));
		// copy to array
		for( i = 0; i< sizeof(FT_PROGRAM_DATA); i++) {
			av_push(array,newSVuv(lpBuffer[i]));
		}
		// give back mem
		free(lpBuffer);
		// return reference of the array
		Data = newRV((SV *) array);
#line 1074 "FTDId2xx.c"
	ST(1) = Data;
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_EE_UASize); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_EE_UASize)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_EE_UASize(ftHandle, dwSize)");
    {
	FT_HANDLE	ftHandle;
	DWORD	dwSize;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 425 "FTDId2xx.xs"
		RETVAL = FT_EE_UASize( ftHandle, &dwSize);
#line 1102 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)dwSize);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_EE_UAWrite); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_EE_UAWrite)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_EE_UAWrite(ftHandle, Data, dwDataLen)");
    {
	FT_HANDLE	ftHandle;
	SV *	Data = ST(1);
	WORD	dwDataLen = (WORD)SvUV(ST(2));
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 436 "FTDId2xx.xs"
		// Data is a reference of a array
		AV * arrayBuffer;
		PUCHAR pData;
		DWORD i;

		if( (!SvROK(Data)) || 
			(SvTYPE(SvRV(Data)) != SVt_PVAV) || 
			(av_len((AV *)SvRV(Data)) < 0)) 
		{
			XSRETURN_UNDEF;
		}

#line 1142 "FTDId2xx.c"
#line 449 "FTDId2xx.xs"
		// copy from array (reference) to buffer
		pData = malloc(dwDataLen);
		arrayBuffer = (AV *)SvRV(Data);
		for(i=0; i<dwDataLen;i++) {
			pData[i] = (char)SvUV(*av_fetch(arrayBuffer,i,0));
		}
		RETVAL = FT_EE_UAWrite(ftHandle, pData, dwDataLen);
		free(pData);
#line 1152 "FTDId2xx.c"
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_EE_UARead); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_EE_UARead)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_EE_UARead(ftHandle, Buffer, nBufferSize, lpBytesReturned)");
    {
	FT_HANDLE	ftHandle;
	SV *	Buffer;
	DWORD	nBufferSize = (DWORD)SvUV(ST(2));
	DWORD	lpBytesReturned;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 467 "FTDId2xx.xs"
		PUCHAR lpBuffer;
		AV * array;
		DWORD i;
#line 1182 "FTDId2xx.c"
#line 471 "FTDId2xx.xs"
		// get mem
		lpBuffer = malloc(nBufferSize);
		RETVAL = FT_EE_UARead(ftHandle, lpBuffer, nBufferSize, &lpBytesReturned);

		// convert output to array
		// new array
		array = (AV *)sv_2mortal((SV *)newAV());
		// extend it ( not required but faster) 
		av_extend(array,lpBytesReturned);
		// copy to array
		for( i = 0; i< lpBytesReturned; i++) {
			av_push(array,newSVuv(lpBuffer[i]));
		}
		// give back mem
		free(lpBuffer);
		// return reference of the array
		Buffer = newRV((SV *) array);
#line 1201 "FTDId2xx.c"
	ST(1) = Buffer;
	SvSETMAGIC(ST(1));
	sv_setuv(ST(3), (UV)lpBytesReturned);
	SvSETMAGIC(ST(3));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetLatencyTimer); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetLatencyTimer)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetLatencyTimer(ftHandle, ucLatency)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	UCHAR	ucLatency = (UCHAR)SvUV(ST(1));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetLatencyTimer(ftHandle, ucLatency);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetLatencyTimer); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetLatencyTimer)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetLatencyTimer(ftHandle, Latency)");
    {
	FT_HANDLE	ftHandle;
	UCHAR	Latency;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 501 "FTDId2xx.xs"
		RETVAL = FT_GetLatencyTimer( ftHandle, &Latency);
#line 1256 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)Latency);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetBitMode); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetBitMode)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetBitMode(ftHandle, ucMask, ucEnable)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	UCHAR	ucMask = (UCHAR)SvUV(ST(1));
	UCHAR	ucEnable = (UCHAR)SvUV(ST(2));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetBitMode(ftHandle, ucMask, ucEnable);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetBitMode); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetBitMode)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetBitMode(ftHandle, Mode)");
    {
	FT_HANDLE	ftHandle;
	UCHAR	Mode = (UCHAR)SvUV(ST(1));
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 516 "FTDId2xx.xs"
		RETVAL = FT_GetBitMode( ftHandle, &Mode );
#line 1310 "FTDId2xx.c"
	sv_setuv(ST(1), (UV)Mode);
	SvSETMAGIC(ST(1));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetUSBParameters); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetUSBParameters)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetUSBParameters(ftHandle, ulInTransferSize, ulOutTransferSize)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	ULONG	ulInTransferSize = (ULONG)SvUV(ST(1));
	ULONG	ulOutTransferSize = (ULONG)SvUV(ST(2));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetUSBParameters(ftHandle, ulInTransferSize, ulOutTransferSize);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetDeadmanTimeout); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetDeadmanTimeout)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetDeadmanTimeout(ftHandle, ulDeadmanTimeout)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	ULONG	ulDeadmanTimeout = (ULONG)SvUV(ST(1));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetDeadmanTimeout(ftHandle, ulDeadmanTimeout);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_GetDeviceInfo); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_GetDeviceInfo)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_GetDeviceInfo(ftHandle, ftDevice, dwID, SerialNumber, Description, Dummy)");
    {
	FT_HANDLE	ftHandle;
	FT_DEVICE	ftDevice = (FT_DEVICE)SvUV(ST(1));
	DWORD	dwID;
	char *	SerialNumber;
	char *	Description;
	SV *	Dummy;
	FT_STATUS	RETVAL;
	dXSTARG;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");
#line 538 "FTDId2xx.xs"
		SerialNumber = malloc(16); // from Databook
		Description = malloc(64);  // from Databook
		RETVAL = FT_GetDeviceInfo( ftHandle, &ftDevice, &dwID, SerialNumber, Description, Dummy);
#line 1395 "FTDId2xx.c"
	sv_setuv(ST(2), (UV)dwID);
	SvSETMAGIC(ST(2));
	sv_setuv(ST(1), (UV)ftDevice);
	SvSETMAGIC(ST(1));
	sv_setpv((SV*)ST(3), SerialNumber);
	SvSETMAGIC(ST(3));
	sv_setpv((SV*)ST(4), Description);
	SvSETMAGIC(ST(4));
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_StopInTask); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_StopInTask)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_StopInTask(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_StopInTask(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_RestartInTask); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_RestartInTask)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_RestartInTask(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_RestartInTask(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_SetResetPipeRetryCount); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_SetResetPipeRetryCount)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_SetResetPipeRetryCount(ftHandle, dwCount)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;
	DWORD	dwCount = (DWORD)SvUV(ST(1));

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_SetResetPipeRetryCount(ftHandle, dwCount);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_ResetPort); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_ResetPort)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_ResetPort(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_ResetPort(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_FTDId2xx_FT_CyclePort); /* prototype to pass -Wmissing-prototypes */
XS(XS_FTDId2xx_FT_CyclePort)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: FTDId2xx::FT_CyclePort(ftHandle)");
    {
	FT_STATUS	RETVAL;
	dXSTARG;
	FT_HANDLE	ftHandle;

	if (SvROK(ST(0))) {
            IV tmp = SvIV((SV*)SvRV(ST(0)));
            ftHandle = *(FT_HANDLE*)INT2PTR(FT_HANDLE,tmp);
        }
        else
            Perl_croak(aTHX_ "ftHandle is not a reference");

	RETVAL = FT_CyclePort(ftHandle);
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_FTDId2xx); /* prototype to pass -Wmissing-prototypes */
XS(boot_FTDId2xx)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("FTDId2xx::FT_Open", XS_FTDId2xx_FT_Open, file, "$$");
        newXSproto("FTDId2xx::FT_OpenEx", XS_FTDId2xx_FT_OpenEx, file, "$$$");
        newXSproto("FTDId2xx::FT_Close", XS_FTDId2xx_FT_Close, file, "$");
        newXSproto("FTDId2xx::FT_CreateDeviceInfoList", XS_FTDId2xx_FT_CreateDeviceInfoList, file, "$");
        newXSproto("FTDId2xx::FT_GetDeviceInfoDetail", XS_FTDId2xx_FT_GetDeviceInfoDetail, file, "$$$$$$$$");
        newXSproto("FTDId2xx::FT_GetDriverVersion", XS_FTDId2xx_FT_GetDriverVersion, file, "$$");
        newXSproto("FTDId2xx::FT_GetLibraryVersion", XS_FTDId2xx_FT_GetLibraryVersion, file, "$");
        newXSproto("FTDId2xx::FT_SetVIDPID", XS_FTDId2xx_FT_SetVIDPID, file, "$$");
        newXSproto("FTDId2xx::FT_GetVIDPID", XS_FTDId2xx_FT_GetVIDPID, file, "$$");
        newXSproto("FTDId2xx::FT_Read", XS_FTDId2xx_FT_Read, file, "$$$$");
        newXSproto("FTDId2xx::FT_Write", XS_FTDId2xx_FT_Write, file, "$$$$");
        newXSproto("FTDId2xx::FT_SetBaudRate", XS_FTDId2xx_FT_SetBaudRate, file, "$$");
        newXSproto("FTDId2xx::FT_SetDivisor", XS_FTDId2xx_FT_SetDivisor, file, "$$");
        newXSproto("FTDId2xx::FT_SetDataCharacteristics", XS_FTDId2xx_FT_SetDataCharacteristics, file, "$$$$");
        newXSproto("FTDId2xx::FT_SetFlowControl", XS_FTDId2xx_FT_SetFlowControl, file, "$$$$");
        newXSproto("FTDId2xx::FT_ResetDevice", XS_FTDId2xx_FT_ResetDevice, file, "$");
        newXSproto("FTDId2xx::FT_SetDtr", XS_FTDId2xx_FT_SetDtr, file, "$");
        newXSproto("FTDId2xx::FT_ClrDtr", XS_FTDId2xx_FT_ClrDtr, file, "$");
        newXSproto("FTDId2xx::FT_SetRts", XS_FTDId2xx_FT_SetRts, file, "$");
        newXSproto("FTDId2xx::FT_ClrRts", XS_FTDId2xx_FT_ClrRts, file, "$");
        newXSproto("FTDId2xx::FT_GetModemStatus", XS_FTDId2xx_FT_GetModemStatus, file, "$$");
        newXSproto("FTDId2xx::FT_SetChars", XS_FTDId2xx_FT_SetChars, file, "$$$$$");
        newXSproto("FTDId2xx::FT_Purge", XS_FTDId2xx_FT_Purge, file, "$$");
        newXSproto("FTDId2xx::FT_SetTimeouts", XS_FTDId2xx_FT_SetTimeouts, file, "$$$");
        newXSproto("FTDId2xx::FT_GetQueueStatus", XS_FTDId2xx_FT_GetQueueStatus, file, "$$");
        newXSproto("FTDId2xx::FT_GetStatus", XS_FTDId2xx_FT_GetStatus, file, "$$$$");
        newXSproto("FTDId2xx::FT_SetBreakOn", XS_FTDId2xx_FT_SetBreakOn, file, "$");
        newXSproto("FTDId2xx::FT_SetBreakOff", XS_FTDId2xx_FT_SetBreakOff, file, "$");
        newXSproto("FTDId2xx::FT_SetWaitMask", XS_FTDId2xx_FT_SetWaitMask, file, "$$");
        newXSproto("FTDId2xx::FT_WaitOnMask", XS_FTDId2xx_FT_WaitOnMask, file, "$$");
        newXSproto("FTDId2xx::FT_GetEventStatus", XS_FTDId2xx_FT_GetEventStatus, file, "$$");
        newXSproto("FTDId2xx::FT_ReadEE", XS_FTDId2xx_FT_ReadEE, file, "$$$");
        newXSproto("FTDId2xx::FT_WriteEE", XS_FTDId2xx_FT_WriteEE, file, "$$$");
        newXSproto("FTDId2xx::FT_EraseEE", XS_FTDId2xx_FT_EraseEE, file, "$");
        newXSproto("FTDId2xx::FT_EE_ProgramByArray", XS_FTDId2xx_FT_EE_ProgramByArray, file, "$$");
        newXSproto("FTDId2xx::FT_EE_ReadToArray", XS_FTDId2xx_FT_EE_ReadToArray, file, "$$");
        newXSproto("FTDId2xx::FT_EE_UASize", XS_FTDId2xx_FT_EE_UASize, file, "$$");
        newXSproto("FTDId2xx::FT_EE_UAWrite", XS_FTDId2xx_FT_EE_UAWrite, file, "$$$");
        newXSproto("FTDId2xx::FT_EE_UARead", XS_FTDId2xx_FT_EE_UARead, file, "$$$$");
        newXSproto("FTDId2xx::FT_SetLatencyTimer", XS_FTDId2xx_FT_SetLatencyTimer, file, "$$");
        newXSproto("FTDId2xx::FT_GetLatencyTimer", XS_FTDId2xx_FT_GetLatencyTimer, file, "$$");
        newXSproto("FTDId2xx::FT_SetBitMode", XS_FTDId2xx_FT_SetBitMode, file, "$$$");
        newXSproto("FTDId2xx::FT_GetBitMode", XS_FTDId2xx_FT_GetBitMode, file, "$$");
        newXSproto("FTDId2xx::FT_SetUSBParameters", XS_FTDId2xx_FT_SetUSBParameters, file, "$$$");
        newXSproto("FTDId2xx::FT_SetDeadmanTimeout", XS_FTDId2xx_FT_SetDeadmanTimeout, file, "$$");
        newXSproto("FTDId2xx::FT_GetDeviceInfo", XS_FTDId2xx_FT_GetDeviceInfo, file, "$$$$$$");
        newXSproto("FTDId2xx::FT_StopInTask", XS_FTDId2xx_FT_StopInTask, file, "$");
        newXSproto("FTDId2xx::FT_RestartInTask", XS_FTDId2xx_FT_RestartInTask, file, "$");
        newXSproto("FTDId2xx::FT_SetResetPipeRetryCount", XS_FTDId2xx_FT_SetResetPipeRetryCount, file, "$$");
        newXSproto("FTDId2xx::FT_ResetPort", XS_FTDId2xx_FT_ResetPort, file, "$");
        newXSproto("FTDId2xx::FT_CyclePort", XS_FTDId2xx_FT_CyclePort, file, "$");
    XSRETURN_YES;
}

